language:
  - c
  - python
before_install:
  - sudo apt-get update
  - sudo apt-get install -y autoconf automake libtool gcc libssl-dev unzip xsltproc python3-pytest
python:
  - "2.7"
#  - "3.5"
  - "3.6"
#  - "3.7"
env:
  - LIBOQS_INSTALL_PATH=/home/travis/liboqs.so
# command to install dependencies
#install:
#  - pip install -r requirements.txt
# command to run tests
script:
  - bash .build_liboqs.sh
  - ls -l /home/travis
  - ls -l /home/travis/build
  - pytest
