language: python
python:
  - "2.7"
#  - "3.5"
  - "3.6"
#  - "3.7"
env:
  - LIBOQS_INSTALL_PATH=/home/travis/liboqs.so
# command to install dependencies
#install:
#  - pip install -r requirements.txt
# command to run tests
script:
  - bash .build_liboqs.sh
  - pytest
